/** Application error code constants */
export enum ErrorCode {
  NOT_FOUND = 'ERR_NOT_FOUND',
  VALIDATION_FAILED = 'ERR_VALIDATION_FAILED',
  UNAUTHORIZED = 'ERR_UNAUTHORIZED',
  FORBIDDEN = 'ERR_FORBIDDEN',
  INTERNAL_ERROR = 'ERR_INTERNAL',
  CONFLICT = 'ERR_CONFLICT',
  RATE_LIMITED = 'ERR_RATE_LIMITED',
  BAD_REQUEST = 'ERR_BAD_REQUEST',
  TIMEOUT = 'ERR_TIMEOUT',
}
